name: Build project for documentation

inputs:
  project:
    description: Project to be built
    required: true
  build_parameters:
    description: Additional build parameters
    required: false

runs:
  using: composite

  steps:
    - name: Checkout
      # Documentation (this) project has already been checked out and moved to the correct directory.
      if: inputs.project != 'doc'
      uses: actions/checkout@v4
      with:
        repository: aidc-toolkit/${{ inputs.project }}
        # Get the matching reference.
        ref: ${{ github.ref_name }}
        path: ${{ inputs.project }}

    - name: Build for documentation
      shell: bash
      working-directory: ${{ inputs.project }}
      run: |
        npm install

        # All projects have build:doc script.
        npm run build:doc -- ${{ inputs.build_parameters }}
