name: Build project for documentation

inputs:
  project:
    required: true
    type: string
  link:
    required: true
    type: boolean
  link_projects:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Checkout ${{ inputs.project }}
      uses: actions/checkout@v4
      with:
        repository: aidc-toolkit/${{ inputs.project }}
        path: ${{ inputs.project }}

    - name: Build ${{ inputs.project }}
      shell: bash
      working-directory: ${{ inputs.project }}
      run: |
        if [ "${{ inputs.link }}" = "true" ]
        then
          npm link
        fi
        for link_project in ${{ inputs.link_projects }}
        do
          npm link @aidc-toolkit/$link_project
        done
        npm ci
        npm install @rollup/rollup-linux-x64-gnu
        npm run build-doc
