name: Build project for documentation

inputs:
  project:
    required: true
    type: string
  no_link:
    required: false
    type: boolean
  link_projects:
    required: false
    type: string
  build_parameters:
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Checkout ${{ inputs.project }}
      if: ${{ inputs.project != 'doc' }}
      uses: actions/checkout@v4
      with:
        repository: aidc-toolkit/${{ inputs.project }}
        path: ${{ inputs.project }}

    # Build includes "npm install @rollup/rollup-linux-x64-gnu", which is necessary to work around platform-specific
    # optional dependencies bug (https://github.com/npm/cli/issues/4828).
    - name: Build ${{ inputs.project }}
      shell: bash
      working-directory: ${{ inputs.project }}
      run: |
        if [ "${{ inputs.no_link }}" != "true" ]
        then
          npm link
        fi
        for link_project in ${{ inputs.link_projects }}
        do
          npm link @aidc-toolkit/$link_project
        done
        npm ci
        npm install @rollup/rollup-linux-x64-gnu
        npm run build-doc -- ${{ inputs.build_parameters }}
