name: Build project for documentation

inputs:
  project:
    description: Project to be built
    required: true
  branch:
    description: Branch to checkout
    required: true
  build_parameters:
    description: Additional build parameters
    required: false

runs:
  using: composite

  steps:
    - name: Checkout
      # Documentation (this) project has already been checked out to the correct directory.
      if: inputs.project != 'doc'
      uses: actions/checkout@v6
      with:
        repository: aidc-toolkit/${{ inputs.project }}
        ref: ${{ inputs.branch }}
        path: ${{ inputs.project }}

    - name: Start terminal session (post build)
      uses: mxschmitt/action-tmate@v3

    - name: Build for documentation
      shell: bash
      working-directory: ${{ inputs.project }}
      run: |
        # Remove package-lock.json; preview build may have references to inaccessible npm registries.
        rm package-lock.json
        
        # Development package has no dependencies.
        if [[ -f ../dependencies ]]
        then
          # Patch dependency versions.
          sh ../patch-dependency-versions.sh
        
          # Link dependencies; must be done all at once.
          xargs npm link < ../dependencies
        
          # Linking packages links to dependencies as well without including them in node_modules/.bin so add the development package path.
          PATH=$PATH:../dev/node_modules/.bin
        fi
        
        # Install remaining dependencies.
        npm install

        # All projects have build:doc script.
        npm run build:doc -- ${{ inputs.build_parameters }}

        # Add this project to the link registry.
        npm link
        
        # Get the version and add to the patch script.
        version=`grep -oP '^  "version": "\K[^"]*' package.json`
        echo "sed -i -e 's/\"@aidc-toolkit\\/${{ inputs.project }}\": \".*\"/\"@aidc-toolkit\\/${{ inputs.project }}\": \"$version\"/' package.json" >> ../patch-dependency-versions.sh
        
        # Add the package name to the list of dependencies.
        echo "@aidc-toolkit/${{ inputs.project }}" >> ../dependencies
