name: Build project for documentation

inputs:
  project:
    description: Project to be built
    required: true
  branch:
    description: Branch to checkout
    required: true
  build_parameters:
    description: Additional build parameters
    required: false

runs:
  using: composite

  steps:
    - name: Checkout
      # Documentation (this) project has already been checked out to the correct directory.
      if: inputs.project != 'doc'
      uses: actions/checkout@v6
      with:
        repository: aidc-toolkit/${{ inputs.project }}
        ref: ${{ inputs.branch }}
        path: ${{ inputs.project }}

    - name: Start terminal session (post build)
      uses: mxschmitt/action-tmate@v3

    - name: Build for documentation
      shell: bash
      working-directory: ${{ inputs.project }}
      run: |
        # Remove package-lock.json; preview build may have references to inaccessible npm registries.
        rm package-lock.json
        
        # Link previous projects.
        sh ../link-all.sh
        
        # Install remaining dependencies.
        npm install

        # All projects have build:doc script.
        npm run build:doc -- ${{ inputs.build_parameters }}

        # Add this project to the link registry and to the script for the next project.
        npm link
        echo "npm link @aidc-toolkit/${{ inputs.project }}" >> ../link-all.sh
