name: Build project for documentation

inputs:
  project:
    description: Project to be built
    required: true
  no_link:
    description: If true, no NPM link is created
    required: false
  link_projects:
    description: List of projects to be linked
    required: false
  build_parameters:
    description: Additional build parameters
    required: false

runs:
  using: composite

  steps:
    - name: Checkout ${{ inputs.project }}
      # Documentation (this) project has already been checked out and moved to the correct directory.
      if: inputs.project != 'doc'
      uses: actions/checkout@v4
      with:
        repository: aidc-toolkit/${{ inputs.project }}
        # Get the matching reference.
        ref: ${{ github.ref_name }}
        path: ${{ inputs.project }}

    - name: Build ${{ inputs.project }}
      shell: bash
      working-directory: ${{ inputs.project }}
      run: |
        # Not all projects are dependencies for other projects.
        if [ "${{ inputs.no_link }}" != "true" ]
        then
          npm link
        fi

        # Link all dependent projects
        for link_project in ${{ inputs.link_projects }}
        do
          npm link @aidc-toolkit/$link_project
        done

        npm ci

        # This is necessary to work around platform-specific optional dependencies bug
        # (https://github.com/npm/cli/issues/4828).
        npm install @rollup/rollup-linux-x64-gnu

        # All projects have build-doc script.
        npm run build-doc -- ${{ inputs.build_parameters }}
