name: Build project for documentation

inputs:
  project:
    required: true
    type: string
  link:
    required: true
    type: boolean
  linked-projects:
    required: false
    type: string

runs:
  using: composite
  steps:
    - name: Checkout ${{ inputs.project }}
      uses: actions/checkout@v4
      with:
        repository: aidc-toolkit/${{ inputs.project }}
        path: ${{ inputs.project }}

    - name: Start terminal session
      uses: mxschmitt/action-tmate@v3

    - name: Build ${{ inputs.project }}
      shell: bash
      working-directory: ${{ inputs.project }}
      run: |
        npm link
        npm link @aidc-toolkit/dev
        npm ci
        npm install @rollup/rollup-linux-x64-gnu
        npm run build-doc

    - name: Start terminal session
      uses: mxschmitt/action-tmate@v3
