name: Build project for documentation

inputs:
  project:
    description: Project to be built
    required: true
  branch:
    description: Branch to checkout
    required: true
  build_parameters:
    description: Additional build parameters
    required: false

runs:
  using: composite

  steps:
    - name: Checkout
      # Documentation (this) project has already been checked out to the correct directory.
      if: inputs.project != 'doc'
      uses: actions/checkout@v6
      with:
        repository: aidc-toolkit/${{ inputs.project }}
        ref: ${{ inputs.branch }}
        path: ${{ inputs.project }}

    - name: Build for documentation
      shell: bash
      working-directory: ${{ inputs.project }}
      run: |
        # Replace organization dependency with link to build directory.
        sed -i -e 's/^    "@aidc-toolkit\/\([^"]*\)": ".*"/    "@aidc-toolkit\/\1": "file:..\/\1"/' package.json
        
        # Install dependencies with copy rather than link to ensure that all are properly available.
        npm install --install-links

        # All projects have build:doc script.
        npm run build:doc -- ${{ inputs.build_parameters }}
