name: Build GitHub Pages

on:
  push:
    branches:
      - main
  release:
    types:
      - published

permissions:
  id-token: write
  pages: write

env:
  NODE_VERSION: 22
  WRITERSIDE_INSTANCE: Writerside/doc
  WRITERSIDE_ARTIFACT: webHelpDOC2-all
  WRITERSIDE_DOCKER_VERSION: 243.21565

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Output some debugging information and exit.
      - name: Debug
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event.ref }}
          echo ${{ github.ref }}
          echo ${{ github.ref_name }}
          exit 1

#      # Insert this at the appropriate step to start a terminal session for debugging.
#      - name: Start terminal session
#        uses: mxschmitt/action-tmate@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Checkout default repository (doc)
        uses: actions/checkout@v4

      - name: Build Writerside artifact
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.WRITERSIDE_INSTANCE }}
          artifact: ${{ env.WRITERSIDE_ARTIFACT }}
          docker-version: ${{ env.WRITERSIDE_DOCKER_VERSION }}

      - name: Finalize doc
        run: |
          # Enable glob expansion.
          shopt -s extglob
          \
          # Create project-specific directory.
          mkdir doc
          \
          # Move all except .github to doc directory.
          mv .!(|.|github) !(doc) doc/
          \
          # Unzip artifact to pages directory
          unzip -O UTF-8 -qq doc/artifacts/${{ env.WRITERSIDE_ARTIFACT }} -d pages

      - name: Start terminal session
        uses: mxschmitt/action-tmate@v3

      - name: Build dev
        uses: ./.github/actions/build-project-doc
        with:
          project: dev

      - name: Build core
        uses: ./.github/actions/build-project-doc
        with:
          project: core
          link_projects: dev

      - name: Build utility
        uses: ./.github/actions/build-project-doc
        with:
          project: utility
          link_projects: dev core

      - name: Build gs1
        uses: ./.github/actions/build-project-doc
        with:
          project: gs1
          link_projects: dev core utility

      - name: Build demo
        uses: ./.github/actions/build-project-doc
        with:
          project: demo
          no_link: true
          link_projects: dev core utility gs1
          build_parameters: --outDir ../pages/demo

      - name: Generate API documentation
        uses: ./.github/actions/build-project-doc
        with:
          project: doc
          no_link: true
          link_projects: dev
          build_parameters: --out ../pages/api

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload pages directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
