name: Build GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

env:
  NODE_VERSION: 22
  WRITERSIDE_INSTANCE: "Writerside/doc"
  WRITERSIDE_ARTIFACT: "webHelpDOC2-all"
  WRITERSIDE_DOCKER_VERSION: "243.21565"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
#      # Insert this at the appropriate step to start a terminal session for debugging.
#      - name: Start terminal session
#        uses: mxschmitt/action-tmate@v3

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: Checkout default repository (doc)
        uses: actions/checkout@v4

      - name: Build Writerside artifact
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: ${{ env.WRITERSIDE_INSTANCE }}
          artifact: ${{ env.WRITERSIDE_ARTIFACT }}
          docker-version: ${{ env.WRITERSIDE_DOCKER_VERSION }}

      - name: Move all except .github to doc directory and unzip artifact to pages directory
        run: |
          shopt -s extglob
          mkdir doc
          mv .!(|.|github) !(doc) doc/
          unzip -O UTF-8 -qq doc/artifacts/${{ env.WRITERSIDE_ARTIFACT }} -d pages

      - name: Build dev
        uses: .github/actions/build-project-doc
        with:
          project: dev

      - name: Build core
        uses: .github/actions/build-project-doc
        with:
          project: core
          link_projects: dev

      - name: Build utility
        uses: .github/actions/build-project-doc
        with:
          project: utility
          link_projects: dev core

      - name: Build gs1
        uses: .github/actions/build-project-doc
        with:
          project: gs1
          link_projects: dev core utility

      - name: Build demo
        uses: .github/actions/build-project-doc
        with:
          project: demo
          no_link: true
          link_projects: dev core utility gs1

      - name: Generate API documentation
        uses: .github/actions/build-project-doc
        with:
          project: doc
          no_link: true
          link_projects: dev
          build_parameters: --out ../pages/api

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Package and upload pages directory
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
